---
services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      target: nginx-bonus
    networks:
      - mandatory
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/blog
      - adm-data:/var/www/adminer
    secrets:
      - wordpress_key
      - wordpress_crt
    restart: always
    depends_on:
      wordpress:
        condition: service_healthy
      adminer:
        condition: service_healthy
      hugo:
        condition: service_started

  # ------------------
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      target: wordpress-bonus
    environment:
      - MDB_USER=${MDB_USER}
      - MDB_PASSWD=${MDB_PASSWD}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PASS=${WP_ADMIN_PASS}
      - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PASS=${WP_USER_PASS}
      - WP_USER_MAIL=${WP_USER_MAIL}
      - REDIS_PASSWD=${REDIS_PASSWD}
    networks:
      - mandatory
    volumes:
      - wp-data:/var/www/blog
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "wordpress", "9000"]
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started

  # ------------------
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      target: mariadb-bonus
    environment:
      - MDB_ROOT_PASSWD=${MDB_ROOT_PASSWD}
      - MDB_HEALTH=${MDB_HEALTH}
      - MDB_HEALTH_PASSWD=${MDB_HEALTH_PASSWD}
      - MDB_USER=${MDB_USER}
      - MDB_PASSWD=${MDB_PASSWD}
      - ADMINER_USER=${ADMINER_USER}
      - ADMINER_PASSWD=${ADMINER_PASSWD}
    networks:
      - mandatory
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--user='${MDB_HEALTH}'", "--password='${MDB_HEALTH_PASSWD}'", "--silent"]

  # ------------------
  redis:
    container_name: redis
    build:
      context: ./requirements/redis
      args:
        - REDIS_PASSWD=${REDIS_PASSWD}
    networks:
      - mandatory
    restart: always
    environment:
      - REDIS_PASSWD=${REDIS_PASSWD}

  # ------------------
  ftp:
    container_name: ftp
    build:
      context: ./requirements/ftp
    networks:
      - mandatory
    restart: always
    depends_on:
      wordpress:
        condition: service_healthy
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASSWD=${FTP_PASSWD}
    volumes:
      - wp-data:/home/${FTP_USER}/
    ports:
      - "21:21"
      - "4200-4242:4200-4242"
    stop_signal: SIGKILL
    secrets:
      - wordpress_key
      - wordpress_crt

  # ------------------
  adminer:
    container_name: adminer
    build:
      context: ./requirements/adminer
    networks:
      - mandatory
    restart: always
    depends_on:
      - mariadb
    volumes:
      - adm-data:/var/www/adminer
    healthcheck:
        test: ["CMD", "nc", "-z", "adminer.mandatory", "9000"]

  # ------------------
  hugo:
    container_name: hugo
    build:
      context: .*/requirements/hugo
    networks:
      - mandatory
    restart: always
    volumes:
      - hugo-data:/var/www/public

# ------------------------------------------------------------------------------
networks:
  mandatory:
    name: "mandatory"
    driver: "bridge"

# ------------------------------------------------------------------------------
volumes:
  wp-data:
    name: wp-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/gtoubol/data/wp-data"

  db-data:
    name: db-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/gtoubol/data/db-data"

  adm-data:
    name: adm-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/gtoubol/data/adm-data"

  hugo-data:
    name: hugo-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/gtoubol/data/hugo-data"

# ------------------------------------------------------------------------------
secrets:
  wordpress_key:
    file: "./cert_utils/${DOMAIN}.key"
  wordpress_crt:
    file: "./cert_utils/${DOMAIN}.crt"
...
