services:
  nginx:
    container_name: nginx
    build: ./nginx
    networks:
      - mandatory
    ports:
      - "80:80"
    volumes:
      - wp-data:/var/www
    restart: always
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build:
      context: ./wordpress
      args:
        MDB_USER: ${MDB_USER}
        MDB_PASSWD: ${MDB_PASSWD}
    networks:
      - mandatory
    volumes:
      - wp-data:/var/www
    restart: always
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
      args:
        MDB_USER: ${MDB_USER}
        MDB_PASSWD: ${MDB_PASSWD}
    networks:
      - mandatory
    volumes:
      - db-data:/var/lib/mysql
    restart: always

networks:
  mandatory:
    name: "mandatory"
    driver: "bridge"

volumes:
  wp-data:
    name: wp-data
  db-data:
    name: db-data
