baseURL = "https://static.gtoubol.42paris.fr/"
buildDrafts = true # To allow configuration
defaultContentLanguage = "en"
title = "Inception showcase"
theme = "terminal"

[Params]
	mainSections = ["post"]
	intro = true
	headline = "my headline"
	description = "an amazing description"
	github = "https://githun.com/GermainToubol"
	email = "germain.toubol.pro@gmail.com"
